### ISSUE TITLE
Duplicated links in documentation

### ISSUE THREAD

**Issue by smaret** [tomchristie/mkdocs#308]
I am trying to use `mkdocs` to document this [project](https://github.com/smaret/lime/tree/doc). I have built the documentation on [read the docs](http://lime.readthedocs.org/en/doc/) sucessfully. However, several links in the menu bar on the left are duplicated. For example, "Introduction" appears twice in the menu bar, although the documentation ([intro.md](https://raw.githubusercontent.com/smaret/lime/doc/doc/usermanual/intro.md) file) contains only one "Introduction" section. How can this be fixed?

**Comment by d0ugal** [comment]
The first is the page title and the second is the introduction section (the H1) on that page.

You could either remove the title for the markdown file or put it in manually with HTML like: `<h1>Introduction</h1>`

**Comment by smaret** [comment]
Thanks for the suggestion, removing the title from the markdown file fixes the problem. I understand that the title is taken from the markdown.yml file, while the section names are taken from the markdown. So if one has a markdown with a title, it appears twice in the TOC.

However I find this a bit counter intuitive. Why not taking the title from the markdown document, if not specified in the yml file?

**Comment by smaret** [comment]
Note that when building documentation from rst on readthedoc, the title is built from the section name in the .rst file. See for example this [file](https://raw.githubusercontent.com/rtfd/readthedocs.org/master/docs/getting_started.rst) which is rendered [here](https://docs.readthedocs.org/en/latest/getting_started.html).

**Comment by d0ugal** [comment]
@smaret We currently do this for the sake of simplicity I think. However, I agree that it would make sense to take the title from the markdown file itself.

**Comment by d0ugal** [comment]
See #316

**Comment by koppor** [comment]
Follow-up seems to be https://github.com/mkdocs/mkdocs/issues/1374.

(This page is the first Google hit for "mkdocs duplicate title")

I have following issue - will try to fix that - without having markdown files without `h1` headings and needing to do some manual configuration.

![grafik](https://user-images.githubusercontent.com/1366654/71934908-bee0f480-31a5-11ea-9979-4a70dea6fe76.png)
