### ISSUE TITLE
gh-deploy from subdirectory

### ISSUE THREAD

**Issue by twiecki** [tomchristie/mkdocs#309]
I am trying to use mkdocs as a sphinx replacement.

It is common for projects to have their docs living in `module_name/docs`. I then would like to do `mkdocs gh-deploy` from the `docs` subdirectory but I get:
```
Cannot deploy - this directory does not appear to be a git repository
```

Any solution?

**Comment by d0ugal** [comment]
I'm not sure I follow. MkDocs has it's documentation under `mkdocs/docs` but we would then run `mkdocs gh-deploy` from the `mkdocs/` directory.

**Comment by twiecki** [comment]
I guess I have `mkdocs/docs/docs` where the config files etc live in `docs/mkdocs.yaml` and the md files live in `mkdocs/docs/docs`.

**Comment by d0ugal** [comment]
Aha, I see. You can probably move your mkdocs.yml to the top level directory and change the `docs_dir` setting to `docs/docs/`.

It would be a reasonable change to make gh-deploy look for the git repo up a few levels.

**Comment by twiecki** [comment]
I guess I can just create the same layout you have and add some directories. E.g. I have `docs/notebooks` which hosts ipython notebooks I convert to markdown so that they can be picked up by mkdocs.

**Comment by d0ugal** [comment]
Yup, that sounds like it will work too.
