### ISSUE TITLE
Allow unhighlighted code

### ISSUE THREAD

**Issue by ePirat** [tomchristie/mkdocs#314]
I can't find a way to make codeblocks without any highlighting (I have some plaintext code blocks, but pygments seems to always guess some language which is wrong)

**Comment by d0ugal** [comment]
Actually, we are not using pygments. The highlighting is handled in the theme. In the MkDocs and ReadTheDocs themes this is done by highlight.js.

**Comment by tomchristie** [comment]
You need to customize the theme if you want to do this.

**Comment by ePirat** [comment]
Oh, is there a reason why not to use pygments?
@tomchristie In my opinion this should be a default thing and not something that someone has to customize.

    ```text
    Foobar this is some text
    ```

should always result in something that is not highlighted…

**Comment by d0ugal** [comment]
I'd suggest you make a request upstream to highlight.js to support a plain/text output.

Doing this in the theme allows the theme to handle it as it wants. You can turn on highlighting in Python-markdown too of course. I'm not sure what happens if you have two enabled tho'

**Comment by ePirat** [comment]
Ok, thanks, that's probably the best option. Did so: isagalaev/highlight.js#700

**Comment by ePirat** [comment]
Figured out that this is actually possible with the `no-highlight` keyword.
(this breaks the RTD theme, see #319)

**Comment by d0ugal** [comment]
Thanks @ePirat
