### ISSUE TITLE
Automatically update the site in gh-page after pushing

### ISSUE THREAD

**Issue by tobegit3hub** [tomchristie/mkdocs#315]
Mkdocs provide the nice feature `mkdocs gh-deploy` to deploy the site in github pages easily. It could be great to make it automatic, just like [jekyll](https://github.com/jekyll/jekyll). And the website is updated when we push the code to master branch.

The implementation could refer to [jekyll-hook](https://github.com/jekyll/jekyll/pull/2617) or git-hook.

**Comment by d0ugal** [comment]
I think it only works on GitHun with Jekyll because they run Jekyll on the GitHub servers, if you want to add a local git hook for this that might do what you need.

**Comment by tobegit3hub** [comment]
We also run mkdocs on GitHub servers. So if mkdocs supports this or add hooks for us, I don't have to implement the git hook by myself for all my mkdocs sites.

**Comment by d0ugal** [comment]
We also run mkdocs on GitHub servers.

You do? How?

**Comment by tobegit3hub** [comment]
The website [runscripts.org](http://runscripts.org/) is on GitHub pages and here's the [source code](https://github.com/runscripts/runscripts.org). It's a typical mkdocs project and we can easily run `mkdocs gh-deploy` to update the static website files in GitHub server.

**Comment by d0ugal** [comment]
Okay, so `jekyll-hook` is it's [own project](https://github.com/developmentseed/jekyll-hook) and it looks like it only works with Jekyll projects, which makes sense. Something similar could be made for MkDocs, but it should live outside of the main project (just like `jekyll-hook` does).
