### ISSUE TITLE
Watchdog Install Issues on OS X Yosemite

### ISSUE THREAD

**Issue by gerrypower** [tomchristie/mkdocs#328]
Just want to note that I had an install issues on Yosemite. The install of the Watchdog dependency was failing as it could not find /usr/bin/gcc-4.2. The resolution that worked for me is noted below - just wanted to log it in case others have the same issue.

Resolution: Link the gcc compiler that is included with Xcode to /usr/bin/gcc-4.2. sudo ln -nsf $(which gcc) /usr/bin/gcc-4.2

**Comment by d0ugal** [comment]
Thanks for the note :)
