### ISSUE TITLE
Chapters with <a id="xyz"> tags are ignored in the TOC

### ISSUE THREAD

**Issue by gunnarbeutner** [tomchristie/mkdocs#335]
Here's an example of a chapter which doesn't show up in my project's TOC:

\# \<a id="test">\</a> Test Chapter

While this works fine:

\# Test Chapter

I can reproduce this behavior using the latest git commit (540b923c8be353ca1f0001323776e551d64d46ba).

**Comment by d0ugal** [comment]
Is this valid markdown syntax? What would you expect the result to be?

**Comment by d0ugal** [comment]
I suspect this is something that would need to be raised upstream with Python-markdown (the markdown lib we use).

**Comment by tomchristie** [comment]
> Here's an example of a chapter which doesn't show up in my project's TOC:
>
> # <a id="test"></a> Test Chapter

Don't do that.

**Comment by gunnarbeutner** [comment]
Considering that Markdown allows inline HTML I would have assumed that this is valid Markdown. Anyway, maybe I should explain what I'm trying to do:

I know that mkdocs (or rather, python-markdown) automatically generates id attributes for its headers (\<h1 id="chapter-title-with-dashes">). While this is convenient I can't use those attributes for two reasons:

1. The ids are non-unique in the unfortunate case when two chapters have the same name.
2. Other Markdown libraries either don't support this feature or are generating their IDs using a different naming scheme.

So, ultimately the \<a id="stuff">\<a> tags I added are there so I have a reliable and unique ID for different chapters.

I've been able to trace this problem to the TOC_LINK_REGEX regex (in mkdocs/toc.py). Apparently it thinks the title for my chapters is "" (as in, an empty string).

If using 'a' tags is not how this is supposed to be done I'm open to suggestions.

**Comment by d0ugal** [comment]
I'd suggest adding `<a id="test"></a>` above or below the header to make that approach work for now.

**Comment by gunnarbeutner** [comment]
I guess that would work - except for the fact that the scroll position wouldn't be properly aligned with the chapter heading. However, instead of doing that I decided to just patch my local mkdocs setup:

    diff --git a/mkdocs/toc.py b/mkdocs/toc.py
    index 410aff5..e2c6acc 100644
    --- a/mkdocs/toc.py
    +++ b/mkdocs/toc.py
    @@ -16,8 +16,8 @@ The steps we take to generate a table of contents are:
    
     import re
    
    -TOC_LINK_REGEX = re.compile('<a href=["]([^"]*)["]>([^<]*)</a>')
    -
    +TOC_LINK_REGEX = re.compile('<a href=["]([^"]*)["]>(.*)</a>')
    +STRIP_HTML_REGEX = re.compile('<.*?>')
    
     class TableOfContents(object):
         """
    @@ -66,6 +66,7 @@ def _parse_html_table_of_contents(html):
             match = TOC_LINK_REGEX.search(line)
             if match:
                 href, title = match.groups()
    +            title = STRIP_HTML_REGEX.sub('', title)
                 nav = AnchorLink(title, href)
                 # Add the item to its parent if required.  If it is a topmost
                 # item then instead append it to our return value.

**Comment by d0ugal** [comment]
What you are doing creates invalid HTML. I wouldn't recommend this approach.

http://www.w3.org/TR/html401/struct/links.html#h-12.2.2

**Comment by gunnarbeutner** [comment]
§12.2.2 specifically deals with nesting \<a> tags inside other \<a> tags. This does not seem to apply here. My patch removes all HTML tags from the chapter title which is used in the TOC (as was probably the intention with the original TOC_LINK_REGEX regex: ([^<]*) matches all characters until the first HTML tag is encountered).

Here's an example TOC:

    <li class="toctree-l1 current">
        <a class="current" href=".">Library Reference</a>
        <ul>
            <li class="toctree-l3"><a href="#library-reference"> Library Reference</a></li>
            <li><a class="toctree-l4" href="#global-functions"> Global functions</a></li>
            <li><a class="toctree-l4" href="#math-object"> Math object</a></li>
            <li><a class="toctree-l4" href="#number-type"> Number type</a></li>
            <li><a class="toctree-l4" href="#boolean-type"> Boolean type</a></li>
            <li><a class="toctree-l4" href="#string-type"> String type</a></li>
            <li><a class="toctree-l4" href="#array-type"> Array type</a></li>
            <li><a class="toctree-l4" href="#dictionary-type"> Dictionary type</a></li>
            <li><a class="toctree-l4" href="#function-type"> Function type</a></li>
        </ul>
    </li>

And here's the chapter heading as it appears in the rendered document:

    <h1 id="library-reference"><a id="id-library-reference"></a> Library Reference</h1>

§4.3.6 in the HTML 5 standard says that nesting \<a> tags inside \<h1> is permitted: http://www.w3.org/TR/html5/sections.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements - The "Content model" for \<h1> specifies that this tag may have child elements which belong to the "Phrasing content" category. This category includes \<a> tags.

**Comment by gunnarbeutner** [comment]
So, considering the lack of replies and the fact that this ticket has been closed can I assume that you don't consider this problem a bug?

**Comment by tomchristie** [comment]
Personally I wouldn't consider it a use case we should put time into supporting at this point, no.
