### ISSUE TITLE
Readthedocs theme isn't up to date when installing mkdocs using pip

### ISSUE THREAD

**Issue by aubort** [tomchristie/mkdocs#336]
Hi there, 

I've just installed mkdocs using `pip install mkdocs`. This worked well, however I faced an issue with the Readthedocs theme which wasn't generating the 2nd level of navigation in the TOC. After some investigation, I found out that the version of the readthedocs theme which is available on github (on master branch) is slightly different than the one installed a few minutes ago. I have now downloaded the latest version from Github and the theme is working well. 

Let me know if you need more detail.

**Comment by d0ugal** [comment]
This is to be expected. We need to do a new release for this to appear on the version pip installs. I'm trying really hard to land #222 before I do a release.

**Comment by aubort** [comment]
Thanks for the quick feedback - I wasn't aware of it. Happy to test it when it's out!
