### ISSUE TITLE
latex math not displayed with mathjax

### ISSUE THREAD

**Issue by twiecki** [tomchristie/mkdocs#356]
We recently switched pymc3 to use mkdocs but it seems that the html produced from the markdown does render math in mathjax: http://pymc-devs.github.io/pymc3/stochastic_volatility/

**Comment by twiecki** [comment]
I tried adding mathjax via `extra_javascript` but to no avail.

**Comment by tomchristie** [comment]
> the html produced from the markdown 

Can you give an example where the markdown renders to HTML incorrectly?

**Comment by twiecki** [comment]
These lines in the html:
```
$$ \sigma \sim Exponential(50) $$

$$ \nu \sim Exponential(.1) $$

$$ s_i \sim Normal(s_{i-1}, \sigma^{-2}) $$

$$ log(\frac{y_i}{y_{i-1}}) \sim t(\nu, 0, exp(-2 s_i)) $$
```

Should be rendered with mathjax.

**Comment by twiecki** [comment]
They look identical in the markdown file but I think the $$ are supposed to trigger mathjax rendering.

**Comment by ci5er** [comment]
You are not the first person to run into this -- and your problem may be in the configuration of the Python Markdown package itself. Take a look at this:
  - http://stackoverflow.com/questions/27882261/mkdocs-and-mathjax

**Comment by twiecki** [comment]
Thanks, works like a charm!

**Comment by blake-arensdorf** [comment]
@twiecki - Can you outline what exactly worked 'like a charm'? I've installed mdx_math and built a site using mkdocs, which seems to render in html correctly (shows up as: '<script type="math/tex; mode=display"> \cos (2\theta) = \cos^2 \theta - \sin^2 \theta </script>'), but when I bring up the site in a browser, that line is simply missing, not rendered as LaTeX.

**Comment by d0ugal** [comment]
@bladorf3 I suspect you are missing the Mathjax JavaScript? You can add this via extra_javascript

**Comment by twiecki** [comment]
Here are the first few lines of the pymc3 mkdocs.yml that got mathjax working:
```
site_name: PyMC3
repo_url: https://github.com/pymc-devs/pymc
site_author: PyMC devs
markdown_extensions: ['extra', 'mathjax']
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','js/mathjaxhelper.js']
```

**Comment by d0ugal** [comment]
And when copying those settings you will also need to add this to your docs directory. https://github.com/pymc-devs/pymc3/blob/master/docs/js/mathjaxhelper.js

**Comment by bladorf3** [comment]
Perfect that worked, thanks guys!
