### ISSUE TITLE
Feature request: specify pre-build script

### ISSUE THREAD

**Issue by twiecki** [tomchristie/mkdocs#357]
I have a script that compiles my IPython NBs to markdown which are then picked up by mkdocs. It'd be nice if I could specify this script to be run on every `mkdocs build`. Something like `pre-build-script: convert_nbs.sh`.

**Comment by d0ugal** [comment]
That could be kinda nice, I guess what you really want is the plugin system see #206 (this probably wont be landing particularly soon). However, other than that, I don't see value in specifying this. Why not just add a `build.sh` file with something like:

    #!/usr/bin/env bash
    convert_nbs.sh
    mkdocs build

**Comment by AdrianSosic** [comment]
Is there nowadays a simple off-the-shelf solution available for this that does not require writing custom plugins?

**Comment by pawamoy** [comment]
[Hooks](https://www.mkdocs.org/user-guide/configuration/#hooks) will let you do that without having to create an installable package 🙂

**Comment by AdrianSosic** [comment]
@pawamoy: Thanks, you just made my day 🌻 For some reason, I just couldn't find it myself ...
