### ISSUE TITLE
Support multistage submenu

### ISSUE THREAD

**Issue by tobegit3hub** [tomchristie/mkdocs#358]
Now we're using mkdocs to host our documents. There're many kinds of documents and we need multistage submenu to display them.

Do you have plans to support this? @d0ugal It means a lot for us :smiley:

**Comment by tomchristie** [comment]
You can do this in a custom theme right?

**Comment by tobegit3hub** [comment]
Can we? I mean we want to add more item in the `Configuration` submenu.

![mkdocs](https://cloud.githubusercontent.com/assets/2715000/6389216/2266e182-bddd-11e4-9e9a-d21b91d51210.png)

We have about 20 projects and each project has several documents. So we have to classify them and put some in the same category. If it supports submenu we can allow each team to provide several documents and display them well.

**Comment by tobegit3hub** [comment]
The screenshot should look like this. We may change the mkdocs.yml to organize the docs but it's worthy :smile: 

![image](https://cloud.githubusercontent.com/assets/2715000/6425320/f0461064-bf5e-11e4-9a14-9b0c370b2377.png)

**Comment by d0ugal** [comment]
We need to do #6 before this makes sense.

However, it sounds like you want to include files in the navigation. I don't think this is something that we want to do. I would suggest creating a download page for each of the 20 projects that each list the files. This should work well, I'm not convinced using navigation for your problem would be nice anyway.

**Comment by tobegit3hub** [comment]
No, I don't want a download page for my projects. I mean there're lot of documents for each project and we can't use mkdocs in this situation. You don't use 20+ categories, right? The multistage submenu could help to support it and allow us to arrange docs easier.

**Comment by d0ugal** [comment]
Okay, fair enough. I missunderstood. So that means #6 is the issue you need to track, that'll solve your problems when somebody gets to it.

**Comment by tobegit3hub** [comment]
You're right. I'm tracking now :smile:
