### ISSUE TITLE
Use CommonMark instead of loosely defined Markdown flavour

### ISSUE THREAD

**Issue by dumblob** [tomchristie/mkdocs#361]
I think that for documentation purposes, the syntax should be precisely defined in advance to allow long-term maintainability, which Gruber's Markdown doesn't fulfill. Therefore I'm suggesting switching from Markdown to [CommonMark](http://commonmark.org/) (there is an existing module https://github.com/rolandshoemaker/CommonMark-py).

**Comment by d0ugal** [comment]
I don't think I see why documentation specifically needs the syntax to be more less precisely defined than other prose, but that is another discussion :)

CommonMark is an intersting project, I appreciate it's goals and may be a direction we wish to take at some point. However, at present it is too young and I don't see any real advantages to switching at this point.

So, we should take note of this and keep an eye on it for the future.

**Comment by dumblob** [comment]
Ok, understood. The nice feature of CommonMark is, that it's backwards compatible, which is the reason why I proposed it even if the spec is still "too young".

**Comment by d0ugal** [comment]
Not just the spec, the implementations too and general uptake. I'll continue to keep an eye on it.

**Comment by d0ugal** [comment]
It's also worth noting that we heavily rely on the Python-Markdown extension system to hook into the build process and grab various bits of information and so on. It is likely that it would be a more disruptive change than you imagine.
