### ISSUE TITLE
Question: Requirement version: Markdown

### ISSUE THREAD

**Issue by peter1000** [tomchristie/mkdocs#363]
hi,

just a question. I came in a conflict with one of my other packages I use which did not work with the Markdown version mkdocs required. I have installed `Markdown-2.6.1`.

What I did I just changes the [requirements.txt](https://github.com/tomchristie/mkdocs/blob/master/requirements.txt#L2)

from `Markdown>=2.3.1,<2.5` to `Markdown>=2.3.1` and installed it.
Seems to work for the `MkDocs`own documentation.

My question is: are there any known issues, reasons you restricted `Markdown <2.5`

Cheers
P

**Comment by d0ugal** [comment]
Markdown 2.5+ dropped Python 2.6 support. We have not formally done this yet.
