### ISSUE TITLE
mkdocs build with alternative link creation

### ISSUE THREAD

**Issue by vbd** [tomchristie/mkdocs#364]
Is there an option that the `mkdocs build` command generates links like
file:///D:/projekte/my/mkdocs-test/site/about/index.html
instead of
file:///D:/projekte/my/mkdocs-test/site/about/

I'm asking cause I want to use the docs without **any** web server. Clicking
on file:///D:/projekte/my/mkdocs-test/site/about/ shows "Index von
D:\projekte\my\mkdocs-test\site\about\" where I have to click on index.html
in Chrome and Firefox both on Windows 8.

**Comment by d0ugal** [comment]
In your config set: `use_directory_urls=false`

**Comment by d0ugal** [comment]
See http://www.mkdocs.org/user-guide/configuration/#preview-controls

**Comment by vbd** [comment]
Thank you very much!
