### ISSUE TITLE
search not working after deployment

### ISSUE THREAD

**Issue by slackmoehrle** [tomchristie/mkdocs#369]
Running MkDocs 0.11.1

Everything is great. I deploy to `slackmoehrle.github.io` and search works as expected.

I copy this site using rsync and search stops working: `cocos2d-x.org/programmersguide`

search also works when running: `mkdocs serve`

what can be the issue here?

**Comment by axilleas** [comment]
Search works for me on `cocos2d-x.org/programmersguide`.

**Comment by d0ugal** [comment]
@slackmoehrle How did you get search to run on 0.11.1? :) search is only being added in #222.

**Comment by slackmoehrle** [comment]
@axilleas - I got it running yesterday at that location finally, turned out to be a path issue that I think is a bug. I just wanted to try my steps again before creating an issue out of it or a PR.

**Comment by slackmoehrle** [comment]
@dougal - I started with 0.11.1 and applied #222. I then fixed a few bugs in js/tipuesearch.js where after executing an initial search any paths would be incorrect if you are not deploying your mkdocs site in root directory. I also added some css to fix the TOC if you have a lot of pages they don't show if you have "Edit on GitHub" enabled. Another user mentioned this fix in a previous GitHub issue and it works and is clean.

**Comment by d0ugal** [comment]
I'm not sure why this is happening. I'm planning on doing lots of work on #222 this weekend, so it'll probably change quite a bit and I suggest you try it then.

**Comment by slackmoehrle** [comment]
I can tell you what I changed. Or if you tell me what need to be done to 222 then I can do the work.

**Comment by d0ugal** [comment]
@slackmoehrle Seeing what you changed would be useful, #222 needs quite a bit of work, I need to refresh myself with it first, it has been a while. I want to explore using something other than Tipue too as it hasn't been great.

**Comment by slackmoehrle** [comment]
ok, let me copy the repo, apply #222, make the edits and send a PR. Can one make a PR to  PR? I'd assume yet. Done the same way?

**Comment by d0ugal** [comment]
Yes, you can - you would want to make a pull request to https://github.com/d0ugal/mkdocs/tree/search

**Comment by damithnh** [comment]
> Yes, you can - you would want to make a pull request to https://github.com/d0ugal/mkdocs/tree/search

Thanks so much
